---
- name: Copying files with permissions
  hosts: servers
  become: true

  tasks:
  - name: Copy a file
    ansible.builtin.copy:
      src: /home/<user-name>/<file-name>
      dest: /tmp/<file-name>
      user: <user-name>
      group: <group-name>
      mode: '0644'
